branch-defaults:
  a2Update:
    environment: my-node-express-project-env
    group_suffix: null
environment-defaults:
  my-node-express-project-env:
    branch: null
    repository: null
global:
  application_name: software-engineering-node
  branch: null
  default_ec2_keyname: Kaushik
  default_platform: Node.js 16
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
