branch-defaults:
  a1:
    environment: null
    group_suffix: null
  a1_section_3:
    environment: Fseassignment-env
  a2:
    environment: my-node-express-project-env
    group_suffix: null
  a2Update:
    environment: my-node-express-project-env
global:
  application_name: software-engineering-node
  branch: null
  default_ec2_keyname: Kaushik
  default_platform: Node.js 16
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
